### PR TITLE
Add IKEv2 SA info to "show vpn ipsec *" options

### PR DESCRIPTION
**Pull request by jhendryUK**
Bug: http://bugzilla.vyos.net/show_bug.cgi?id=388

Add IKEv2 SA information to the output of "show vpn ipsec *" commands

### CODE REVIEW

**Comment by jhendryUK** [comment]
The patch currently has no concept of newestike/newestspi as that information is not displayed in the output of 'ipsec statusall'.  Maybe the output of `ipsec statusall` is ordered so the newest is printed last?  I dont know but we should probably figure it out, somehow...

**Comment by stigt** [comment]
Nice, this was on my todo list.  Is this also supposed to fix "show vpn ike
sa" with ikev2?  I noticed that the local/remote subnet are not shown in
"show vpn ipsec sa detail", but this is definitely better than no output.

stig

**Comment by jhendryUK** [comment]
Hi,  this was not supposed to fix "show vpn ike sa", I will look at that and see what I can do.   The local/remote subnets are reported in my test lab, can you send me the output of "sudo ipsec statusall"?  I should be able to fix it from that.

**Comment by jhendryUK** [comment]
My previous commit has a typo in a variable name, %ike_hash should be %esp_hash.  Is it worth me doing another commit to fix that?

**Comment by dmbaturin** [comment]
Yes, please do. Push in the same branch you created the pul request from and it will be automatically updated.

**Comment by stigt** [comment]
Hi Jason,

Sorry for the delay - Thanksgiving holiday there.

## ubnt@R2:~$ show vpn ipsec sa detail

Peer IP:                20.0.0.2
Peer ID:                20.0.0.2
Local IP:               30.0.0.2
Local ID:               30.0.0.2
NAT Traversal:          no
NAT Source Port:        n/a
NAT Dest Port:          n/a

```
Tunnel 1:
    State:                  up
    Inbound SPI:            c1605187
    Outbound SPI:           cebb4d77
    Encryption:             aes128
    Hash:                   sha1_96
    PFS Group:              default

    Local Net:              n/a
    Local Protocol:         all
    Local Port:             all

    Remote Net:             n/a
    Remote Protocol:        all
    Remote Port:            all

    Inbound Bytes:          86.0M
    Outbound Bytes:         4.8M
    Active Time (s):        960
    Lifetime (s):           3600
```

ubnt@R2:~$ sudo ipsec statusall
000 Status of IKEv1 pluto daemon (strongSwan 4.5.2):
000 interface lo/lo ::1:500
000 interface lo/lo 127.0.0.1:4500
000 interface lo/lo 127.0.0.1:500
000 interface eth0/eth0 30.0.0.2:4500
000 interface eth0/eth0 30.0.0.2:500
000 interface eth1/eth1 172.16.1.1:4500
000 interface eth1/eth1 172.16.1.1:500
000 interface eth2/eth2 172.16.2.1:4500
000 interface eth2/eth2 172.16.2.1:500
000 %myid = '%any'
000 loaded plugins: test-vectors curl ldap aes des sha1 sha2 md5
random x509 pkcs1 pgp dnskey pem openssl gmp hmac xauth attr
kernel-netlink resolve
000 debug options: none
000
Status of IKEv2 charon daemon (strongSwan 4.5.2):
  uptime: 2 minutes, since Jun 01 10:00:37 2014
  malloc: sbrk 242080, mmap 0, used 153848, free 88232
  worker threads: 7 idle of 16, job queue load: 0, scheduled events: 5
  loaded plugins: test-vectors curl ldap aes des sha1 sha2 md5 random
x509 revocation constraints pubkey pkcs1 pgp pem openssl fips-prf gmp
agent pkcs11 xcbc hmac ctr ccm gcm attr kernel-netlink resolve
socket-raw farp stroke updown eap-identity eap-aka eap-md5 eap-gtc
eap-mschapv2 eap-radius eap-tls eap-ttls eap-tnc dhcp addrblock
Listening IP addresses:
  30.0.0.2
  172.16.1.1
  172.16.2.1
Connections:
peer-20.0.0.2-tunnel-1:  30.0.0.2...20.0.0.2
peer-20.0.0.2-tunnel-1:   local:  [30.0.0.2] uses pre-shared key authentication
peer-20.0.0.2-tunnel-1:   remote: [20.0.0.2] uses any authentication
peer-20.0.0.2-tunnel-1:   child:  172.16.1.0/24 === 192.168.1.0/24
Routed Connections:
peer-20.0.0.2-tunnel-1{1}:  ROUTED, TUNNEL
peer-20.0.0.2-tunnel-1{1}:   172.16.1.0/24 === 192.168.1.0/24
Security Associations:
peer-20.0.0.2-tunnel-1[2]: ESTABLISHED 2 minutes ago,
30.0.0.2[30.0.0.2]...20.0.0.2[20.0.0.2]
peer-20.0.0.2-tunnel-1[2]: IKE SPIs: ba8e7d58735aa788_i*
96938c68ed4470e7_r, pre-shared key reauthentication in 7 hours
peer-20.0.0.2-tunnel-1[2]: IKE proposal:
AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_2048
peer-20.0.0.2-tunnel-1{3}:  INSTALLED, TUNNEL, ESP SPIs: c1605187_i cebb4d77_o
peer-20.0.0.2-tunnel-1{3}:  AES_CBC_128/HMAC_SHA1_96, 90190314 bytes_i
(49s ago), 5006124 bytes_o (49s ago), rekeying in 44 minutes
peer-20.0.0.2-tunnel-1{3}:   172.16.1.0/24 === 192.168.1.0/24

**Comment by jhendryUK** [comment]
Hey Stigt,

No problem on the wait, last weekend was my birthday so never had time to doing any coding anyway...

Thanks for the output, I raised a new bug ticket. Should be fixed here: http://bugzilla.vyos.net/show_bug.cgi?id=398

**Comment by stigt** [comment]
Thanks jhendryUK.  The patch worked for my configuration, so I pulled it into ubnt's repo also.

**Pull request merged**
