### PR TITLE
Fixing output of "show vpn ike sa" when reauth=no

### PR DESCRIPTION
**Pull request by jhendryUK**
Bug: http://bugzilla.vyos.net/show_bug.cgi?id=396

Fixing output of "show vpn ike sa" when reauth=no

### CODE REVIEW

**Comment by stigt** [comment]
Hi Jason,

I pulled your other ikev2 changes and now "show vpn ike sa" does work with
ikev2 - Nice!   But when I changed one side to be a 0.0.0.0 peer and
connection type respond, then "show vpn ike sa" doesn't work on the 0.0.0.0
and also the stats are missing.

ubnt@R1:~$ show vpn ike sa
ubnt@R1:~$
ubnt@R1:~$ show vpn ipsec sa
Peer ID / IP                            Local ID / IP

---

30.0.0.2
20.0.0.2

```
Tunnel  State  Bytes Out/In   Encrypt  Hash  NAT-T  A-Time  L-Time
```

Proto

##     ------  -----  -------------  -------  ----  -----  ------  ------

```
1       up     n/a            n/a      n/a   no     0       3600    all
```

## ubnt@R1:~$ show vpn ipsec sa detail

Peer IP:                30.0.0.2
Peer ID:                30.0.0.2
Local IP:               20.0.0.2
Local ID:               20.0.0.2
NAT Traversal:          no
NAT Source Port:        n/a
NAT Dest Port:          n/a

```
Tunnel 1:
    State:                  up
    Inbound SPI:            c4265bd3
    Outbound SPI:           cd6f971a
    Encryption:             n/a
    Hash:                   n/a
    PFS Group:              default

    Local Net:              n/a
    Local Protocol:         all
    Local Port:             all

    Remote Net:             n/a
    Remote Protocol:        all
    Remote Port:            all

    Inbound Bytes:          0.0
    Outbound Bytes:         0.0
    Active Time (s):        0
    Lifetime (s):           3600
```

ubnt@R1:~$ sudo ipsec statusall
000 Status of IKEv1 pluto daemon (strongSwan 4.5.2):
000 interface lo/lo ::1:500
000 interface lo/lo 127.0.0.1:4500
000 interface lo/lo 127.0.0.1:500
000 interface eth0/eth0 20.0.0.2:4500
000 interface eth0/eth0 20.0.0.2:500
000 interface eth1/eth1 192.168.1.1:4500
000 interface eth1/eth1 192.168.1.1:500
000 interface eth2/eth2 192.168.2.1:4500
000 interface eth2/eth2 192.168.2.1:500
000 %myid = '%any'
000 loaded plugins: test-vectors curl ldap aes des sha1 sha2 md5 random
x509 pkcs1 pgp dnskey pem openssl gmp hmac xauth attr kernel-netlink
resolve
000 debug options: none
000
Status of IKEv2 charon daemon (strongSwan 4.5.2):
  uptime: 6 minutes, since Jun 01 10:00:37 2014
  malloc: sbrk 242080, mmap 0, used 152064, free 90016
  worker threads: 7 idle of 16, job queue load: 0, scheduled events: 0
  loaded plugins: test-vectors curl ldap aes des sha1 sha2 md5 random x509
revocation constraints pubkey pkcs1 pgp pem openssl fips-prf gmp agent
pkcs11 xcbc hmac ctr ccm gcm attr kernel-netlink resolve socket-raw farp
stroke updown eap-identity eap-aka eap-md5 eap-gtc eap-mschapv2 eap-radius
eap-tls eap-ttls eap-tnc dhcp addrblock
Listening IP addresses:
  20.0.0.2
  192.168.1.1
  192.168.2.1
Connections:
peer-0.0.0.0-tunnel-1:  20.0.0.2...%any
peer-0.0.0.0-tunnel-1:   local:  [20.0.0.2] uses pre-shared key
authentication
peer-0.0.0.0-tunnel-1:   remote: [%any] uses any authentication
peer-0.0.0.0-tunnel-1:   child:  192.168.1.0/24 === 172.16.1.0/24
Security Associations:
peer-0.0.0.0-tunnel-1[1]: ESTABLISHED 6 minutes ago,
20.0.0.2[20.0.0.2]...30.0.0.2[30.0.0.2]
peer-0.0.0.0-tunnel-1[1]: IKE SPIs: dde69757a671f804_i 78c7abea79472368_r*,
rekeying disabled
peer-0.0.0.0-tunnel-1[1]: IKE proposal:
AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_2048
peer-0.0.0.0-tunnel-1{1}:  INSTALLED, TUNNEL, ESP SPIs: c4265bd3_i
cd6f971a_o
peer-0.0.0.0-tunnel-1{1}:  AES_CBC_128/HMAC_SHA1_96, 5043784 bytes_i (244s
ago), 92374904 bytes_o (244s ago), rekeying disabled
peer-0.0.0.0-tunnel-1{1}:   192.168.1.0/24 === 172.16.1.0/24

**Comment by stigt** [comment]
Hi Jason,

Couple questions:

1) my ikev1 configs seem to come up automatically, but when I change the
same config to use ikev2 it seems ike is up, but the tunnel doesn't seem to
come up until data causes it to come up.  Have you observed the same thing?

2) Have you tried ikev2 with vti interfaces?  So far I can't seem to get
vti to work even though the tunnel says established

ubnt@R2:~$ show vpn ipsec sa
Peer ID / IP                            Local ID / IP

---

20.0.0.2
30.0.0.2

```
Tunnel  State  Bytes Out/In   Encrypt  Hash  NAT-T  A-Time  L-Time
```

Proto

##     ------  -----  -------------  -------  ----  -----  ------  ------

```
vti     down   0.0/0.0        aes128   sha1_96 no     -1440
```

all

ubnt@R2:~$ sudo ipsec statusall
000 Status of IKEv1 pluto daemon (strongSwan 4.5.2):
000 interface lo/lo ::1:500
000 interface lo/lo 127.0.0.1:4500
000 interface lo/lo 127.0.0.1:500
000 interface eth0/eth0 30.0.0.2:4500
000 interface eth0/eth0 30.0.0.2:500
000 interface eth1/eth1 172.16.1.1:4500
000 interface eth1/eth1 172.16.1.1:500
000 interface eth2/eth2 172.16.2.1:4500
000 interface eth2/eth2 172.16.2.1:500
000 %myid = '%any'
000 loaded plugins: test-vectors curl ldap aes des sha1 sha2 md5 random
x509 pkcs1 pgp dnskey pem openssl gmp hmac xauth attr kernel-netlink
resolve
000 debug options: none
000
Status of IKEv2 charon daemon (strongSwan 4.5.2):
  uptime: 24 minutes, since Jun 01 10:00:50 2014
  malloc: sbrk 242080, mmap 0, used 143024, free 99056
  worker threads: 7 idle of 16, job queue load: 0, scheduled events: 5
  loaded plugins: test-vectors curl ldap aes des sha1 sha2 md5 random x509
revocation constraints pubkey pkcs1 pgp pem openssl fips-prf gmp agent
pkcs11 xcbc hmac ctr ccm gcm attr kernel-netlink resolve socket-raw farp
stroke updown eap-identity eap-aka eap-md5 eap-gtc eap-mschapv2 eap-radius
eap-tls eap-ttls eap-tnc dhcp addrblock
Listening IP addresses:
  30.0.0.2
  172.16.1.1
  172.16.2.1
Connections:
peer-20.0.0.2-tunnel-vti:  30.0.0.2...20.0.0.2
peer-20.0.0.2-tunnel-vti:   local:  [30.0.0.2] uses pre-shared key
authentication
peer-20.0.0.2-tunnel-vti:   remote: [20.0.0.2] uses any authentication
peer-20.0.0.2-tunnel-vti:   child:  0.0.0.0/0 === 0.0.0.0/0
Routed Connections:
peer-20.0.0.2-tunnel-vti{1}:  ROUTED, TUNNEL
peer-20.0.0.2-tunnel-vti{1}:   0.0.0.0/0 === 0.0.0.0/0
Security Associations:
peer-20.0.0.2-tunnel-vti[2]: ESTABLISHED 24 minutes ago,
30.0.0.2[30.0.0.2]...20.0.0.2[20.0.0.2]
peer-20.0.0.2-tunnel-vti[2]: IKE SPIs: 82ef6e54820ec630_i
bfd900e7085a2f24_r*, pre-shared key reauthentication in 7 hours
peer-20.0.0.2-tunnel-vti[2]: IKE proposal:
AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_2048
peer-20.0.0.2-tunnel-vti{3}:  INSTALLED, TUNNEL, ESP SPIs: c7a0ce0f_i
ce9f185e_o
peer-20.0.0.2-tunnel-vti{3}:  AES_CBC_128/HMAC_SHA1_96, 0 bytes_i, 0
bytes_o, rekeying in 24 minutes
peer-20.0.0.2-tunnel-vti{3}:   0.0.0.0/0 === 0.0.0.0/0

**Comment by jhendryUK** [comment]
Hi Stigt,

I have a patch ready to fix both the scenarios you have mentioned so far (VTI config + When you changed the peer to be 0.0.0.0 and connection-type to respond).  Problem is that the patches for these changes the same line as a previous PullRequest I have, I am a git noob and not quite sure how to go about this properly.

In the mean time I am going to hold onto the patch for the 2 scenarios, when the other PullRequest has been merged I will then create another to fix the above issues.

As for the tunnel not coming up until it has had data in it, I am running OSPF in all my tunnels so I have not witnessed this, I will create a few extra ones today and see what happens.

**Comment by alexharpin** [comment]
Hi Stigt,

With regards to this comment

"2) Have you tried ikev2 with vti interfaces? So far I can't seem to get vti to work even though the tunnel says established"

Are you seeing that the VTI comes up as expected but can't pass any traffic, or that the tunnel doesn't come up at all?  If it's the former then it's more than likely down to Bug #358 (http://bugzilla.vyos.net/show_bug.cgi?id=358), I'm committing changes to resolve this on Thursday, haven't had enough (any) spare time to track this down until now.

**Comment by dmbaturin** [comment]
Current nightly builds should have the original VTI bug fixed, but if you spot more problems, please tell. 1.1.0 release images certainly do have that bug.

**Comment by jhendryUK** [comment]
Hi Stigt,

"show vpn ipsec sa" is now fixed when peer is 0.0.0.0 and connection-type=respond. (  http://bugzilla.vyos.net/show_bug.cgi?id=401  )

**Comment by stigt** [comment]
Awesome, I'll try it out tomorrow.

**Pull request merged**
